### ISSUE TITLE
USER STORY: Submit a Poll Response

### ISSUE THREAD

**Issue by Koby1705** [Koby1705/My-First-Agile-Project#3]
In order to **receive benefit** as a **role**, I can **goal / desire**
## Acceptance Criteria:
* The option should be provided as a checkbox
* The checkbox should be “checked” by default
## Tasks:
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Test the functionality
